name: docker-ci

# タグのpushで走らせる
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: API Build and push docker image
        run: |
          TAG=$(echo ${GITHUB_REF} | grep -o "v[0-9][\.].*")
          DOCKER_IMAGE=mitsugu1128/todo-server-api:$TAG
          echo "Docker image: ${DOCKER_IMAGE}"
          docker login --username="${{ secrets.DOCKER_USERNAME }}" --password="${{ secrets.DOCKER_PASSWORD }}"
          docker build -f ./build/docker/api/Dockerfile -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: Gateway Build and push docker image
        run: |
          TAG=$(echo ${GITHUB_REF} | grep -o "v[0-9][\.].*")
          DOCKER_IMAGE=mitsugu1128/todo-server-gateway:$TAG
          echo "Docker image: ${DOCKER_IMAGE}"
          docker login --username="${{ secrets.DOCKER_USERNAME }}" --password="${{ secrets.DOCKER_PASSWORD }}"
          docker build -f ./build/docker/gateway/Dockerfile -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE