name: docker-ci

# タグのpushで走らせる
on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_IMAGE_API_NAME: mitsugu1128/todo-server-api
  DOCKER_IMAGE_GATEWAY_NAME: mitsugu1128/todo-server-gateway

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: create tag
        run: |
          export TAG=$(echo ${GITHUB_REF} | grep -o "v[0-9][\.].*")
          echo "TAGS=$TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: API Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./build/docker/api/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: true
          tags: ${{ env.TAGS }}

      - name: Gateway Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./build/docker/gateway/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: true
          tags: ${{ env.TAGS }}