name: docker-ci

# タグのpushで走らせる
on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_IMAGE_API_NAME: mitsugu1128/todo-server-api
  DOCKER_IMAGE_GATEWAY_NAME: mitsugu1128/todo-server-gateway

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: API Build and push docker image
        run: |
          TAG=$(echo ${GITHUB_REF} | grep -o "[0-9][\.].*")
          DOCKER_IMAGE=${DOCKER_IMAGE_API_NAME}:${TAG}
          echo "Docker image: ${DOCKER_IMAGE}"
          docker login --username="${{ secrets.DOCKER_USERNAME }}" --password="${{ secrets.DOCKER_PASSWORD }}"
          docker build -f ./build/docker/api/Dockerfile -t ${DOCKER_IMAGE} .
          docker push mitsugu1128/todo-server-api:${TAG}

      - name: Gateway Build and push docker image
        run: |
          TAG=$(echo ${GITHUB_REF} | grep -o "[0-9][\.].*")
          DOCKER_IMAGE=${DOCKER_IMAGE_GATEWAY_NAME}:${TAG}
          echo "Docker image: ${DOCKER_IMAGE}"
          docker login --username="${{ secrets.DOCKER_USERNAME }}" --password="${{ secrets.DOCKER_PASSWORD }}"
          docker build -f ./build/docker/gateway/Dockerfile -t ${DOCKER_IMAGE} .
          docker push mitsugu1128/todo-server-gateway:${TAG}